# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7052226662bcbbf9160ed68b1dbed36d2ecbd18e817a69933a1887021d390634d61a604a10448da337b90b81964a31a3eb5dfaa127a09b14b344fb32d37d664

test:
  secret_key_base: 7445023ce78b19cd1d0d6eab4ccae40e73ec5d29fa94d9d8b085972340b49f67c170dd5196b5de4808c6f19717f3a1f19deff57211ebf16af7065f0e65cdab32

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
